import { CUSTOMER, VESSELS, TECHNOLOGIES, TECHNICIANS } from '../config/appConfig'

export async function generateJobCardPDF(jobData) {
  // Dynamically import html2pdf
  const html2pdf = (await import('html2pdf.js')).default

  const vessel = VESSELS.find(v => v.id === jobData.vessel)
  const technology = TECHNOLOGIES.find(t => t.id === jobData.technology)
  const technician1 = TECHNICIANS.find(t => t.id === jobData.technician1)
  const technician2 = TECHNICIANS.find(t => t.id === jobData.technician2)
  const technicianNames = [technician1?.name, technician2?.name].filter(Boolean).join(', ')

  const html = `
    <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 800px; margin: 0 auto;">
      <div style="text-align: center; margin-bottom: 30px; border-bottom: 2px solid #1e3a5f; padding-bottom: 20px;">
        <h1 style="color: #1e3a5f; margin: 0;">${CUSTOMER.name} Job Report</h1>
        <h2 style="color: #64748b; margin: 10px 0;">Job Card: ${jobData.jobNumber}</h2>
      </div>

      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px;">
        <div style="background: #f8fafc; padding: 15px; border-radius: 8px;">
          <h3 style="margin: 0 0 10px 0; color: #1e3a5f;">Job Information</h3>
          <p><strong>Date:</strong> ${jobData.date}</p>
          <p><strong>Vessel:</strong> ${vessel?.name || jobData.vessel}</p>
          <p><strong>Technology:</strong> ${technology?.name || jobData.technology}</p>
          <p><strong>Technician(s):</strong> ${technicianNames || 'Not assigned'}</p>
          <p><strong>Status:</strong> ${jobData.status}</p>
        </div>
      </div>

      <div style="margin-bottom: 30px;">
        <h3 style="color: #1e3a5f; border-bottom: 1px solid #e2e8f0; padding-bottom: 10px;">Equipment Inspected</h3>
        <table style="width: 100%; border-collapse: collapse;">
          <thead>
            <tr style="background: #1e3a5f; color: white;">
              <th style="padding: 10px; text-align: left;">Equipment</th>
              <th style="padding: 10px; text-align: left;">Area</th>
              <th style="padding: 10px; text-align: left;">Condition</th>
              <th style="padding: 10px; text-align: left;">Notes</th>
            </tr>
          </thead>
          <tbody>
            ${jobData.equipment?.map((eq, i) => `
              <tr style="background: ${i % 2 === 0 ? '#f8fafc' : 'white'};">
                <td style="padding: 10px; border-bottom: 1px solid #e2e8f0;">${eq.equipmentDesc}</td>
                <td style="padding: 10px; border-bottom: 1px solid #e2e8f0;">${eq.area}</td>
                <td style="padding: 10px; border-bottom: 1px solid #e2e8f0;">
                  <span style="padding: 4px 8px; border-radius: 4px; background: ${
                    eq.condition === 'critical' ? '#fee2e2' : 
                    eq.condition === 'attention' ? '#fef3c7' : '#dcfce7'
                  }; color: ${
                    eq.condition === 'critical' ? '#991b1b' : 
                    eq.condition === 'attention' ? '#92400e' : '#166534'
                  };">${eq.condition}</span>
                </td>
                <td style="padding: 10px; border-bottom: 1px solid #e2e8f0;">${eq.notes || '-'}</td>
              </tr>
            `).join('') || '<tr><td colspan="4" style="padding: 20px; text-align: center;">No equipment selected</td></tr>'}
          </tbody>
        </table>
      </div>

      ${jobData.notes ? `
        <div style="margin-bottom: 20px;">
          <h3 style="color: #1e3a5f;">Notes</h3>
          <p style="background: #f8fafc; padding: 15px; border-radius: 8px;">${jobData.notes}</p>
        </div>
      ` : ''}

      ${jobData.findings ? `
        <div style="margin-bottom: 20px;">
          <h3 style="color: #1e3a5f;">Findings</h3>
          <p style="background: #f8fafc; padding: 15px; border-radius: 8px;">${jobData.findings}</p>
        </div>
      ` : ''}

      ${jobData.recommendations ? `
        <div style="margin-bottom: 20px;">
          <h3 style="color: #1e3a5f;">Recommendations</h3>
          <p style="background: #f8fafc; padding: 15px; border-radius: 8px;">${jobData.recommendations}</p>
        </div>
      ` : ''}

      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; text-align: center; color: #64748b; font-size: 12px;">
        <p>Generated by ${CUSTOMER.name} Job Report System</p>
        <p>© ${new Date().getFullYear()} WearCheck Reliability Solutions</p>
      </div>
    </div>
  `

  const element = document.createElement('div')
  element.innerHTML = html

  const opt = {
    margin: 10,
    filename: `${jobData.jobNumber}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
  }

  await html2pdf().set(opt).from(element).save()
}

export default { generateJobCardPDF }
